version: "3"

services:
  wg-easy:
    container_name: wg-easy
    image: "weejewel/wg-easy"
    network_mode: "bridge"
    restart: always      
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/etc/wireguard

    environment:
      - TZ=Asia/Jakarta
      - WG_HOST=wg.hostname.anda
      - WG_DEFAULT_DNS=192.168.1.1
      - PASSWORD=password
