version: "3"

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: "louislam/uptime-kuma:1"
    network_mode: "bridge"  
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Jakarta